modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"
issueTrackerURL="https://github.com/Ultrasquid9/Recharged/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
logoFile="recharged_title.png"
displayName="${mod_name}"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

### Dependencies ###

[[dependencies.recharged]]
	modId="neoforge"
	type="required"
	versionRange="${neo_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.recharged]]
	modId="minecraft"
	type="required"
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"
